### ISSUE TITLE
The localization page is horribly wrong.

### ISSUE THREAD

**Issue by crlf0710** [ruse-lang/ruse-lang.github.io#3]
Hi. Do you know that the localized page is horribly wrong?

It says something like: "Ruse - One way to embedded script inside Rust.", and translated "Scheme" into "one way".

I think it needs to be fixed.

**Comment by crlf0710** [comment]
It also translated "stress-free project" into something like "have fun during learning" which is not very accurate i think.

**Comment by crlf0710** [comment]
It also removed the paragraphs "If you’re looking for a real-world-ready programming language to solve some immediate problem, best look elsewhere." and "The Ruse team maintains a list of other programming languages implemented in Rust, which you may be interested in perusing."

**Comment by 3442853561** [comment]
I have fixed these controversial translations.

**Comment by alilleybrinker** [comment]
Thanks for the info! I have merged the changes @3442853561 submitted. If there are any more issues, let me know. :smile:

**Comment by crlf0710** [comment]
~~Looks much better now. 😄~~

Edit: Errr... No. It shouldn't be "Scheme scheme". "Scheme" is not a scheme at all 😄 It's a language in its own right.
